### ISSUE TITLE
Run error

### ISSUE THREAD

**Issue by yangbing668** [raghavian/lungVAE#1]
"Image = TF.rotate(image,angle)" in "dataset.py" reports an error at runtime "TypeError: function takes exactly 1 argument (3 given)" How to solve it, thank you very much!

**Comment by raghavian** [comment]
Looks like one of your arguments to TF.rotate() is a tuple? Can you print the dimensions of image data? 
You could also disable rotation augmentation by setting rot=0 when you load the dataset in [train.py](https://github.com/raghavian/lungVAE/blob/master/train.py#L48).
