### ISSUE TITLE
torch load .pt returns tuple and not dict

### ISSUE THREAD

**Issue by bartmch** [raghavian/lungVAE#2]
Hi, using your .pt file I tried to load it `torch.load(args.model,map_location=device)` which return a tuple of two tensors and not a dict. As a result `net.load_state_dict(torch.load(args.model,map_location=device))` returns an error 

> 'tuple' object has no attribute 'copy'

I'm using the earliest compatible torch version with Cuda 10.1 which is 1.5 - It's impossible to revert my cuda version. Any idea how I can resolve this issue?

**Comment by raghavian** [comment]
Can you verify if you are trying to use the saved model that is provided? As far as I see it is a dict and does not depend on the version of CUDA/Pytorch.

**Comment by bartmch** [comment]
I tried it again this morning and it ran fine - I think I had a bad config in my VS code. Thanks
